/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IGrommetIconsGithub: typeof import('~icons/grommet-icons/github')['default']
    IGrommetIconsLinkedid: typeof import('~icons/grommet-icons/linkedid')['default']
    IGrommetIconsLinkedin: typeof import('~icons/grommet-icons/linkedin')['default']
    IGrommetIconsMail: typeof import('~icons/grommet-icons/mail')['default']
    IMdiAccount: typeof import('~icons/mdi/account')['default']
    PianoKey: typeof import('./src/components/piano/PianoKey.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheBubbles: typeof import('./src/components/TheBubbles.vue')['default']
    TheFireworks: typeof import('./src/components/TheFireworks.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    ThePiano: typeof import('./src/components/ThePiano.vue')['default']
  }
}
